package:
  name: rockyridge
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/pythonflaskserverapps/rockyridge.git

requirements:
  build:
    - python
    - setuptools
  run:
    

test:
  imports:
    - rockyridge

about:
  home: https://github.com/pythonflaskserverapps/rockyridge
  license: MIT
  license_file: LICENSE
